### ISSUE TITLE
Provide beta branch for nightly SDK

### ISSUE THREAD

**Issue by CodedOre** [flathub/org.freedesktop.Sdk.Extension.vala#26]
As of now, this extension can't be used with the Gnome SDK from the nightly repository.
Could it be considered to add an beta branch based on `22.08beta` to provide the extension for the nightly SDK as well?

**Comment by lw64** [comment]
the ``21.08beta`` branch is not updated since August 2021 anymore. Why do you need that for the GNOME nightly Sdk?

**Comment by CodedOre** [comment]
Sorry, my mistake, should have been `22.08beta`, not `21`...

The reason is that the nightly Gnome SDK builds on `22.08beta`, not on `22.08`, so if you want to use the extension with the nightly Gnome SDK it's not possible as it can't find the dependency.

**Comment by tinywrkb** [comment]
> The reason is that the nightly Gnome SDK builds on 22.08beta

Why would you use this extension for Gnome?

**Comment by CodedOre** [comment]
> Why would you use this extension for Gnome?

As I understand it, this extension provides the development tools for Vala, like the language server, and would allow to use them in a enviroment fully using Flatpak, like Fedora Silverblue. Since developing of these apps often is based on the nightly SDK, it would be great to support the extension for said SDK.

Apart from that: Gnome Builder 43 will add the extension to the manifest of any new Vala project, and the nightly builds of Builder create invalid manifest since it uses the nightly SDK.

**Comment by tinywrkb** [comment]
> As I understand it, this extension provides the development tools for Vala, like the language server, and would allow to use them in a enviroment fully using Flatpak, like Fedora Silverblue. Since developing of these apps often is based on the nightly SDK, it would be great to support the extension for said SDK.

You already have everything needed in the Gnome SDK, and as far as I can tell the language server is vscode specific, so I don't see the point using this extension with the Gnome SDK.

> Apart from that: Gnome Builder 43 will add the extension to the manifest of any new Vala project, and the nightly builds of Builder create invalid manifest since it uses the nightly SDK.

The one in Flathub is 42, and it uses the Freedesktop runtime.  

I can't comment about Builder's behavior, but I will say that a not that great decision made by the developers of the Freedesktop runtime is to automatically add every SDK extension's libdir to the ld.so config.  
As a user, you have zero control over this, and it can potentially break applications.  
Don't believe me? Drop a broken `libc.so` in an SDK extension's libdir, or one belongs to a different libc implementation than GNU's, and see that nothing that depends on an SDK runtime is able to run.

My point is, it's a terrible idea to mix and match shared libs and toolchains that are already in the runtime with others from an SDK extension, so don't use this extension with the Gnome SDK.
