### ISSUE TITLE
"desktop" is misspelled in readme

### ISSUE THREAD

**Issue by K4rakara** [flathub/org.freedesktop.Sdk.Extension.vala#84]
I figured this out the hard way after quite a bit of frustration and head scratching until I found the typo in the text I copy/pasted.

[This](https://github.com/flathub/org.freedesktop.Sdk.Extension.vala/blob/branch/22.08/README.md?plain=1#L17) is the offending line. "desktop" is misspelled as "dektop".

**Comment by lw64** [comment]
sorry, took some a little time...
